1. data array

1.1 Create an array using Python lists

In [8]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m


[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [9]:
m[1]


[0.5, 0.75, 1.0, 1.5, 2.0]

In [10]:
m[1][0]


0.5

In [11]:
v1=[0.5,1.5]
v2=[1,2]
m=[v1,v2]
c=[m,m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [12]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m


[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [13]:
v[0] = 'python'
m

[['python', 0.75, 1.0, 1.5, 2.0],
 ['python', 0.75, 1.0, 1.5, 2.0],
 ['python', 0.75, 1.0, 1.5, 2.0]]

In [14]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v)]
m


[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [15]:
v[0]='python'
m


[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

2.2 Python array type

In [16]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
import array 
a = array.array('f', v)
a


array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [17]:
a.append(0.5)
a


array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [18]:
a.extend([5.0,6.75])
a


array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [19]:
2*a
 

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [20]:
a.append('string')

TypeError: must be real number, not str

In [21]:
a.tolist()


[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [22]:
f = open('array.apy','wb')
a.tofile(f)
f.close()



In [23]:
b = array.array('f')
with open('array.apy','rb') as f:
    b.fromfile(f,5)
b

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [27]:
b = array.array('d')
with open('array.apy','rb') as f:
    b.fromfile(f,2)
b

EOFError: read() didn't return enough bytes

4.2 Regular numpy array

4.2.1 basic knowledge


In [28]:
import numpy as np
a=np.array([0,0.5,1.0,1.5,2.0])
a


array([0. , 0.5, 1. , 1.5, 2. ])

In [29]:
type(a) 

numpy.ndarray

In [30]:
a = np.array(['a','b','c'])
a


array(['a', 'b', 'c'], dtype='<U1')

In [32]:
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
a = np.arange(8,dtype=np.float32)
a

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [36]:
a[5:]

array([5., 6., 7.], dtype=float32)

In [37]:
a[:2]

array([0., 1.], dtype=float32)

In [38]:
a.sum() 


np.float32(28.0)

In [39]:
a.std()

np.float32(2.291288)

In [40]:
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.], dtype=float32)

In [44]:
l = [0., 0.5,1.5,3.,5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [45]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [46]:
2 * a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.], dtype=float32)

In [47]:
a ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.], dtype=float32)

In [49]:
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05], dtype=float32)

In [50]:
np.exp(a)


array([1.0000000e+00, 2.7182817e+00, 7.3890562e+00, 2.0085537e+01,
       5.4598148e+01, 1.4841316e+02, 4.0342880e+02, 1.0966332e+03],
      dtype=float32)

In [51]:
np.sqrt(a)

array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512], dtype=float32)

In [52]:
np.sqrt(2.5)

np.float64(1.5811388300841898)

In [53]:
import math

In [54]:
math.sqrt(2.5)

1.5811388300841898

In [55]:
math.sqrt(a)

TypeError: only 0-dimensional arrays can be converted to Python scalars

In [56]:
%timeit np.sqrt(2.5)

57.9 ns ± 1.05 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [58]:
%timeit math.sqrt(2.5)

15.2 ns ± 0.155 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


4.2.2 multidimensional array

In [60]:
b = np.array([a,a*2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]], dtype=float32)

In [61]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [62]:
b[0,2]

np.float32(2.0)

In [63]:
b[:,1]

array([1., 2.], dtype=float32)

In [64]:
b.sum()

np.float32(84.0)

In [65]:
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.], dtype=float32)

In [66]:
b.sum(axis=1)

array([28., 56.], dtype=float32)

In [67]:
c=np.zeros((2,3),dtype='i',order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [72]:
c=np.ones((2,3,4),dtype='i',order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [75]:
e = np.empty((2,3,2))
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [76]:
f= np.empty_like(c)
f

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [77]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
g =np.linspace(5,15,12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])