5.1 DataFrame

5.1.1 the first step to use dataframe

In [1]:
import pandas as pd
df = pd.DataFrame([10,20,30,40],columns=['numbers'],index=['a','b','c','d'])
df


,numbers
a,10
b,20
c,30
d,40


In [2]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [3]:
df.columns

Index(['numbers'], dtype='str')

In [4]:
df.loc['c']

numbers    30
Name: c, dtype: int64

In [6]:
df.loc[['a','d']]


,numbers
a,10
d,40


In [7]:
df.iloc[1:3]

,numbers
b,20
c,30


In [8]:
df.sum()

numbers    100
dtype: int64

In [9]:
df.apply(lambda x: x**2)

,numbers
a,100
b,400
c,900
d,1600


In [10]:
df**2

,numbers
a,100
b,400
c,900
d,1600


In [11]:
df['float'] = (1.5,2.5,3.5,4.5)
df

,numbers,float
a,10,1.5
b,20,2.5
c,30,3.5
d,40,4.5


In [12]:
df['float']
df

,numbers,float
a,10,1.5
b,20,2.5
c,30,3.5
d,40,4.5


In [13]:
df['name'] = pd.DataFrame(['Yves','Sandra','Lilli','Henry'],index=['d','a','b','c'])
df

,numbers,float,name
a,10,1.5,Sandra
b,20,2.5,Lilli
c,30,3.5,Henry
d,40,4.5,Yves


In [23]:
df.loc['y'] = {'numbers':100,'floats':5.75,'name':'JIL'}
df


,numbers,float,name
a,10,1.5,Sandra
b,20,2.5,Lilli
c,30,3.5,Henry
d,40,4.5,Yves
y,100,NaN,JIL


In [24]:
df.dtypes

numbers      int64
float      float64
name           str
dtype: object

In [27]:
df[['numbers','float']].mean()


numbers    40.0
float       3.0
dtype: float64

In [28]:
df[['numbers','float']].std()

numbers    35.355339
float       1.290994
dtype: float64

5.1.2 The second step to use Pandas

In [1]:
import numpy as np
np.random.seed(100)
a = np.random.standard_normal((9,4))
a


array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ,  0.73100034,  1.36155613],
       [-0.32623806,  0.05567601,  0.22239961, -1.443217  ],
       [-0.75635231,  0.81645401,  0.75044476, -0.45594693]])

In [3]:
import pandas as pd
df = pd.DataFrame(a)
df

,0,1,2,3
0,-1.749765,0.342680,1.153036,-0.252436
1,0.981321,0.514219,0.221180,-1.070043
2,-0.189496,0.255001,-0.458027,0.435163
3,-0.583595,0.816847,0.672721,-0.104411
4,-0.531280,1.029733,-0.438136,-1.118318
5,1.618982,1.541605,-0.251879,-0.842436
6,0.184519,0.937082,0.731000,1.361556
7,-0.326238,0.055676,0.222400,-1.443217
8,-0.756352,0.816454,0.750445,-0.455947


In [4]:
df.columns = ['No1','No2','No3','No4']
df

,No1,No2,No3,No4
0,-1.749765,0.342680,1.153036,-0.252436
1,0.981321,0.514219,0.221180,-1.070043
2,-0.189496,0.255001,-0.458027,0.435163
3,-0.583595,0.816847,0.672721,-0.104411
4,-0.531280,1.029733,-0.438136,-1.118318
5,1.618982,1.541605,-0.251879,-0.842436
6,0.184519,0.937082,0.731000,1.361556
7,-0.326238,0.055676,0.222400,-1.443217
8,-0.756352,0.816454,0.750445,-0.455947


In [5]:
df['No2'].mean()


np.float64(0.701033094145646)

In [8]:
dates = pd.date_range('2019-1-1',periods=9,freq='ME')
dates


DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30'],
              dtype='datetime64[us]', freq='ME')

In [9]:
df.index=dates
df

,No1,No2,No3,No4
2019-01-31,-1.749765,0.342680,1.153036,-0.252436
2019-02-28,0.981321,0.514219,0.221180,-1.070043
2019-03-31,-0.189496,0.255001,-0.458027,0.435163
2019-04-30,-0.583595,0.816847,0.672721,-0.104411
2019-05-31,-0.531280,1.029733,-0.438136,-1.118318
2019-06-30,1.618982,1.541605,-0.251879,-0.842436
2019-07-31,0.184519,0.937082,0.731000,1.361556
2019-08-31,-0.326238,0.055676,0.222400,-1.443217
2019-09-30,-0.756352,0.816454,0.750445,-0.455947


In [10]:
df.values

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ,  0.73100034,  1.36155613],
       [-0.32623806,  0.05567601,  0.22239961, -1.443217  ],
       [-0.75635231,  0.81645401,  0.75044476, -0.45594693]])

In [11]:
np.array(df)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ,  0.73100034,  1.36155613],
       [-0.32623806,  0.05567601,  0.22239961, -1.443217  ],
       [-0.75635231,  0.81645401,  0.75044476, -0.45594693]])