6.1 Object Overview

6.1.1 int

In [ ]:
n = 5
type(n)

int

In [ ]:
n.numerator

5

In [ ]:
n.bit_length()


3

In [ ]:
n + n

10

In [ ]:
2*n

10

In [ ]:
n.__sizeof__()


28

6.1.2 list

In [ ]:
l = [1, 2, 3, 4]
type(l)

list

In [ ]:
l[0]

1

In [ ]:
l.append(10)
l

[1, 2, 3, 4, 10]

In [ ]:
l+l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [ ]:
2*l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [ ]:
sum(l)

20

In [ ]:
l.__sizeof__()


104

6.1.3 ndarray

In [ ]:
import numpy as np
a = np.arange(16).reshape((4,4))
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.dtype


dtype('int64')

In [ ]:
a.sum()

np.int64(120)

In [ ]:
a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [ ]:
a+a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [ ]:
2*a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [ ]:
sum(a)

array([24, 28, 32, 36])

In [ ]:
np.sum(a)

np.int64(120)

In [ ]:
a.__sizeof__()

128

6.2 foundation

In [ ]:
class FinancialInstrument(object):
    pass
fi = FinancialInstrument()
type(fi)


__main__.FinancialInstrument

In [ ]:
fi

In [ ]:
fi.__str__()

'<__main__.FinancialInstrument object at 0x1043639e0>'

In [ ]:
fi.price = 100
fi.price

100

In [ ]:
class FinancialInstrument(object):
    author = 'Yves Hilpisch'
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.price = price
FinancialInstrument.author


'Yves Hilpisch'

In [ ]:
aapl = FinancialInstrument('AAPL', 100)
aapl.symbol

'AAPL'

In [ ]:
aapl.author

'Yves Hilpisch'

In [ ]:
aapl.price=105
aapl.price


105

In [ ]:
class FinancialInstrument(object):
    author = 'Yves Hilpisch'
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.price = price
    def get_price(self):         
        return self.price
    def set_price(self, new_price):  
        self.price = new_price
fi = FinancialInstrument('AAPL', 100)
fi.get_price()


100

In [ ]:
fi.set_price(105)
fi.get_price()

105

In [ ]:
fi.price

105

In [ ]:
class PortfolioPosition(object):
    def __init__(self, financial_instruments,position_size):
        self.position = financial_instruments
        self.__position_size = position_size
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size() * self.__position_get_price()
pp = PortfolioPosition(fi, 10)
pp.get_position_size()


10

In [ ]:
pp.position.set_price(105)
pp.position.get_price()


105

6.3 Vector class

In [ ]:
class Vector(object):
    def __init__(self, x=0, y=0,z=0):
        self.x = x
        self.y = y
        self.z = z
def __repr__(self):
    return 'Vector(%r,%r,%r)' % (self.x,self.y,self.z)
def __abs__(self):
    return (self.x**2 + self.y**2 + self.z**2)**0.5
def __bool__(self):
    return bool(abs(self))
def __add__(self,other):
  x = self.x + other.x
  y = self.y + other.y
  z = self.z + other.z
  return Vector(x,y,z)
def __mul__(self,scalar):
  x = self.x * scalar
  y = self.y * scalar
  z = self.z * scalar
def __len__(self):
  return 3
def __getitem__(self,i):
   if i in [0,-3]:
       return self.x
   elif i in [1,-2]:
       return self.y
   elif i in [2,-1]:
       return self.z
   else:
       raise IndexError('Vector index out of range')
def __iter__(self):
   for i in range(len(self)):
       yield self[i]
  
