6.1 Object Overview

6.1.1 int

In [1]:
n = 5
type(n)

int

In [2]:
n.numerator

5

In [3]:
n.bit_length()


3

In [4]:
n + n

10

In [5]:
2*n

10

In [6]:
n.__sizeof__()


28

6.1.2 list

In [7]:
l = [1, 2, 3, 4]
type(l)

list

In [8]:
l[0]

1

In [9]:
l.append(10)
l

[1, 2, 3, 4, 10]

In [10]:
l+l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [11]:
2*l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [12]:
sum(l)

20

In [13]:
l.__sizeof__()


104

6.1.3 ndarray

In [1]:
import numpy as np
a = np.arange(16).reshape((4,4))
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [2]:
type(a)

numpy.ndarray

In [3]:
a.dtype


dtype('int64')

In [4]:
a.sum()

np.int64(120)

In [6]:
a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [7]:
a+a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [8]:
2*a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [9]:
sum(a)

array([24, 28, 32, 36])

In [10]:
np.sum(a)

np.int64(120)

In [11]:
a.__sizeof__()

128

6.2 foundation

In [15]:
class FinancialInstrument(object):
    pass
fi = FinancialInstrument()
type(fi)


__main__.FinancialInstrument

In [16]:
fi

In [17]:
fi.__str__()

'<__main__.FinancialInstrument object at 0x1157cd670>'

In [18]:
fi.price = 100
fi.price

100

In [19]:
class FinancialInstrument(object):
    author = 'Yves Hilpisch'
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.price = price
FinancialInstrument.author


'Yves Hilpisch'

In [20]:
aapl = FinancialInstrument('AAPL', 100)
aapl.symbol

'AAPL'

In [21]:
aapl.author

'Yves Hilpisch'

In [24]:
aapl.price=105
aapl.price


105